/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false --strict-vars=false` (hash: 93b5f801f8c6d567b3ea8bb9b97bf31f)
interface __BaseEnv_Env {
	CORE: D1Database;
	ENTORNO: string;
	ZONA_HORARIA: string;
	BILLETERA: DurableObjectNamespace<import("./src/index").BilleteraDO>;
	SECUENCIA: DurableObjectNamespace<import("./src/index").SecuenciaDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BilleteraDO" | "SecuenciaDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENTORNO" | "ZONA_HORARIA">> {}
}
