/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=staging --include-runtime=false` (hash: ca8c7c7076371f911faee9c662aa291b)
interface __BaseEnv_Env {
	CORE: D1Database;
	ENTORNO: "staging";
	ZONA_HORARIA: "America/Asuncion";
	BILLETERA: DurableObjectNamespace<import("./src/index").BilleteraDO>;
	SECUENCIA: DurableObjectNamespace<import("./src/index").SecuenciaDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BilleteraDO" | "SecuenciaDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENTORNO" | "ZONA_HORARIA">> {}
}
