#!/usr/bin/env node
/**
 * Oraculo: los tipos de los bindings tienen que salir de `wrangler.jsonc`, no de
 * una copia escrita a mano.
 *
 * El defecto que motiva esto lo encontro una auditoria de esta misma entrega, y
 * lo midio en las dos direcciones sobre `src/index.ts`:
 *
 *   · Se agrego una var a `wrangler.jsonc` y NO a `Entorno`: `tsc` limpio, 50
 *     pruebas verdes, 12 del runtime verdes. Nada falla; el Worker simplemente
 *     no la ve.
 *   · Se declaro en `Entorno` un `PAGOS: DurableObjectNamespace<...>` y un
 *     `CLAVE_BANCARIA: string` que `wrangler.jsonc` no tiene: `tsc` limpio. En
 *     runtime valen `undefined` sin un solo ruido, y el codigo que los use
 *     explota con `Cannot read properties of undefined`.
 *
 * O sea: `Entorno` era un doble de la configuracion, y nada lo comparaba contra
 * el original. Es el mismo agujero que `check-esquema.mjs` cierra entre
 * TypeScript y el SQL de las migraciones, en otra frontera.
 *
 * Como se cierra: `wrangler types` genera la interfaz DESDE la configuracion.
 * `worker-configuration.d.ts` no se escribe a mano nunca — se regenera y se
 * compara. Y en `pruebas-runtime/runtime.test.ts` hay una linea que le pide a
 * TypeScript que `Entorno` sea satisfecho por el `Cloudflare.Env` generado, asi
 * que un `Entorno` que promete de mas no compila.
 *
 * Por que regenerar y comparar, y no `wrangler types --check`: medido, `--check`
 * sale 1 cuando cambio `wrangler.jsonc` (bien) pero sale 0 cuando alguien EDITA
 * el archivo generado (mal — compara un hash de la configuracion, no el
 * contenido). Un oraculo que no nota que le tocaron el archivo que custodia no
 * sirve. Regenerar y comparar el contenido entero cubre los dos casos.
 *
 * Uso:  node herramientas/check-entorno.mjs
 */

import { readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'

const RAIZ = fileURLToPath(new URL('..', import.meta.url))
const GENERADO = 'worker-configuration.d.ts'

/**
 * Los argumentos con los que se genera. Van en una constante y no repetidos en
 * dos lugares: si el comando de la documentacion y el del oraculo divergen, el
 * oraculo compara contra algo que nadie genera.
 *
 * `--include-runtime=false` deja el archivo en menos de 1 KB en vez de 543 KB:
 * los tipos del runtime ya los trae `@cloudflare/workers-types`, que es
 * dependencia igual. Lo unico que hace falta generar es el `Env`.
 */
export const ARGUMENTOS = [
  'wrangler',
  'types',
  '--env',
  'staging',
  '--include-runtime=false',
  '--path',
]

/**
 * Compara dos textos ignorando el final de linea, para que el veredicto no
 * cambie entre Windows y Linux. El defecto n.º 6 de la Fase 0 fue exactamente
 * eso: el mismo commit fallaba en Windows y pasaba en el CI.
 *
 * Y descarta UNA linea: la que wrangler escribe con el comando que uso para
 * generar. Esa linea embute la ruta absoluta de salida y un hash calculado sobre
 * ella, asi que regenerar a un temporal la cambia siempre:
 *
 *     // Generated by Wrangler by running `wrangler types ... /tmp/xxx/w.d.ts` (hash: acbf...)
 *     // Generated by Wrangler by running `wrangler types ...`                 (hash: ca8c...)
 *
 * Se reemplaza por un marcador en los dos lados —en vez de borrarla— para que
 * los numeros de linea que reporta el error sigan siendo los del archivo de
 * verdad. Lo que se pierde es el chequeo del `hash`, y no importa: el hash es un
 * resumen de la configuracion, y aca se compara el contenido entero, que es
 * estrictamente mas fuerte.
 */
export function compararGenerado(comprometido, regenerado) {
  const normalizar = (s) =>
    s
      .replace(/\r\n/g, '\n')
      .replace(/^\/\/ Generated by Wrangler by running .*$/m, '// (encabezado de wrangler)')
      .trimEnd()
  const a = normalizar(comprometido)
  const b = normalizar(regenerado)
  if (a === b) return { ok: true, lineaDistinta: null, esperada: null, encontrada: null }

  const la = a.split('\n')
  const lb = b.split('\n')
  for (let i = 0; i < Math.max(la.length, lb.length); i += 1) {
    if (la[i] !== lb[i]) {
      return { ok: false, lineaDistinta: i + 1, esperada: lb[i] ?? '(no existe)', encontrada: la[i] ?? '(no existe)' }
    }
  }
  return { ok: false, lineaDistinta: null, esperada: null, encontrada: null }
}

function main() {
  let comprometido
  try {
    comprometido = readFileSync(join(RAIZ, GENERADO), 'utf8')
  } catch {
    console.error('')
    console.error(`  check-entorno: FALTA ${GENERADO}`)
    console.error('')
    console.error('  Es el archivo que le da tipos a los bindings, generado desde')
    console.error('  wrangler.jsonc. Se regenera con:')
    console.error('')
    console.error(`      npx ${ARGUMENTOS.join(' ')} ${GENERADO}`)
    console.error('')
    process.exit(1)
  }

  // El temporal va en la RAIZ DEL REPOSITORIO, no en /tmp. No es pereza: el
  // archivo generado contiene `import("./src/index")`, una ruta relativa a su
  // propia ubicacion. Generado en /tmp, wrangler escribe
  // `import("../../root/recargaya-platform/src/index")` y la comparacion nunca
  // puede coincidir. Se borra en el `finally`, y esta en .gitignore por si el
  // proceso muere en el medio.
  const destino = join(RAIZ, '.check-entorno.temporal.d.ts')

  try {
    const r = spawnSync('npx', [...ARGUMENTOS, destino], { cwd: RAIZ, encoding: 'utf8' })
    if (r.status !== 0) {
      console.error('')
      console.error('  check-entorno: `wrangler types` FALLO')
      console.error('')
      console.error(`    ${(r.stderr || r.stdout || '').trim().split('\n').slice(-3).join('\n    ')}`)
      console.error('')
      process.exit(1)
    }

    const cmp = compararGenerado(comprometido, readFileSync(destino, 'utf8'))

    if (!cmp.ok) {
      console.error('')
      console.error(`  check-entorno: ${GENERADO} NO COINCIDE CON wrangler.jsonc`)
      console.error('')
      if (cmp.lineaDistinta !== null) {
        console.error(`    primera diferencia, linea ${cmp.lineaDistinta}:`)
        console.error(`      en el repositorio : ${cmp.encontrada}`)
        console.error(`      deberia decir     : ${cmp.esperada}`)
        console.error('')
      }
      console.error('  O cambio la configuracion y nadie regenero los tipos, o alguien edito')
      console.error('  el archivo generado a mano. Las dos cosas terminan igual: el codigo')
      console.error('  compila contra bindings que no existen, y en runtime valen undefined')
      console.error('  sin un solo ruido.')
      console.error('')
      console.error('  Se arregla regenerando, nunca editando:')
      console.error('')
      console.error(`      npx ${ARGUMENTOS.join(' ')} ${GENERADO}`)
      console.error('')
      process.exit(1)
    }
  } finally {
    rmSync(destino, { force: true })
  }

  console.log(`  check-entorno: OK — ${GENERADO} coincide con wrangler.jsonc`)
}

if (import.meta.main) main()
