#!/usr/bin/env node
/**
 * Oraculo: los tipos de los bindings tienen que salir de `wrangler.jsonc`, no de
 * una copia escrita a mano.
 *
 * El defecto que motiva esto lo encontro una auditoria de esta misma entrega, y
 * lo midio en las dos direcciones sobre `src/index.ts`:
 *
 *   · Se agrego una var a `wrangler.jsonc` y NO a `Entorno`: `tsc` limpio, 50
 *     pruebas verdes, 12 del runtime verdes. Nada falla; el Worker simplemente
 *     no la ve.
 *   · Se declaro en `Entorno` un `PAGOS: DurableObjectNamespace<...>` y un
 *     `CLAVE_BANCARIA: string` que `wrangler.jsonc` no tiene: `tsc` limpio. En
 *     runtime valen `undefined` sin un solo ruido, y el codigo que los use
 *     explota con `Cannot read properties of undefined`.
 *
 * O sea: `Entorno` era un doble de la configuracion, y nada lo comparaba contra
 * el original. Es el mismo agujero que `check-esquema.mjs` cierra entre
 * TypeScript y el SQL de las migraciones, en otra frontera.
 *
 * Como se cierra: `wrangler types` genera la interfaz DESDE la configuracion.
 * `worker-configuration.d.ts` no se escribe a mano nunca — se regenera y se
 * compara. Y en `pruebas-runtime/runtime.test.ts` hay una linea que le pide a
 * TypeScript que `Entorno` sea satisfecho por el `Cloudflare.Env` generado, asi
 * que un `Entorno` que promete de mas no compila.
 *
 * Por que regenerar y comparar, y no `wrangler types --check`: medido, `--check`
 * sale 1 cuando cambio `wrangler.jsonc` (bien) pero sale 0 cuando alguien EDITA
 * el archivo generado (mal — compara un hash de la configuracion, no el
 * contenido). Un oraculo que no nota que le tocaron el archivo que custodia no
 * sirve. Regenerar y comparar el contenido entero cubre los dos casos.
 *
 * Uso:  node herramientas/check-entorno.mjs
 */

import { readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { invocadoDirecto } from './invocado-directo.mjs'

const RAIZ = fileURLToPath(new URL('..', import.meta.url))
export const GENERADO = 'worker-configuration.d.ts'

/**
 * El entorno sale del mismo archivo de datos que lee el arnes de pruebas, y no
 * de un literal 'staging' aca.
 *
 * Es un arreglo de la segunda vuelta de auditoria: `check-runtime.mjs` se tomo el
 * trabajo de no suponer el entorno —«si el arnes y el oraculo miran entornos
 * distintos, el oraculo no mide lo que corre»— y este archivo, escrito en el
 * mismo commit, lo suponia. El dia que el arnes apunte a otro entorno, `Entorno`
 * quedaria comparado contra los bindings del equivocado.
 */
const ENTORNO_DE_PRUEBAS = JSON.parse(
  readFileSync(join(RAIZ, 'pruebas-runtime', 'entorno-de-pruebas.json'), 'utf8'),
).environment

/**
 * Los argumentos con los que se genera. Van en una constante y no repetidos en
 * dos lugares: si el comando de la documentacion y el del oraculo divergen, el
 * oraculo compara contra algo que nadie genera.
 *
 * `--include-runtime=false` deja el archivo en menos de 1 KB en vez de 543 KB:
 * los tipos del runtime ya los trae `@cloudflare/workers-types`, que es
 * dependencia igual. Lo unico que hace falta generar es el `Env`.
 */
export const ARGUMENTOS = [
  'wrangler',
  'types',
  '--env',
  ENTORNO_DE_PRUEBAS,
  '--include-runtime=false',
  // Sin esto, wrangler tipa cada var como su literal (`ENTORNO: "staging"`) y la
  // comprobacion de asignabilidad mutua de `pruebas-runtime/runtime.test.ts` no
  // puede cerrar: `Entorno` declara `string`, y `string` no es asignable a
  // `"staging"`. Con las dos direcciones cerradas se agarra un binding que falta
  // en `Entorno`, uno vuelto opcional, uno ensanchado y uno con el tipo cambiado.
  // Lo que se pierde es el literal, que `Entorno` no declaraba igual.
  '--strict-vars=false',
  '--path',
]

/**
 * Compara dos textos ignorando el final de linea, para que el veredicto no
 * cambie entre Windows y Linux. El defecto n.º 6 de la Fase 0 fue exactamente
 * eso: el mismo commit fallaba en Windows y pasaba en el CI.
 *
 * Y descarta UNA linea: la que wrangler escribe con el comando que uso para
 * generar. Esa linea embute la ruta de salida, asi que regenerar a otro nombre de
 * archivo la cambia siempre:
 *
 *     // Generated by Wrangler by running `wrangler types ...`                    (hash: ca8c...)
 *     // Generated by Wrangler by running `wrangler types ... .temporal.d.ts`      (hash: ca8c...)
 *
 * (El `hash` NO depende de la ruta: es un resumen de la configuracion, y medido,
 * sale identico en los dos lados. Una version anterior de este comentario decia
 * que el hash se calculaba sobre la ruta y mostraba dos hashes distintos como
 * evidencia. Era falso, y los dos hashes estaban inventados.)
 *
 * Se reemplaza por un marcador en los dos lados —en vez de borrarla— para que los
 * numeros de linea que reporta el error sigan siendo los del archivo de verdad.
 * Lo que se pierde es el chequeo del `hash`, y no importa: aca se compara el
 * contenido entero, que es estrictamente mas fuerte.
 */
export function compararGenerado(comprometido, regenerado) {
  const normalizar = (s) =>
    s
      .replace(/\r\n/g, '\n')
      .replace(/^\/\/ Generated by Wrangler by running .*$/m, '// (encabezado de wrangler)')
      .trimEnd()
  const a = normalizar(comprometido)
  const b = normalizar(regenerado)
  if (a === b) return { ok: true, lineaDistinta: null, esperada: null, encontrada: null }

  const la = a.split('\n')
  const lb = b.split('\n')
  for (let i = 0; i < Math.max(la.length, lb.length); i += 1) {
    if (la[i] !== lb[i]) {
      return { ok: false, lineaDistinta: i + 1, esperada: lb[i] ?? '(no existe)', encontrada: la[i] ?? '(no existe)' }
    }
  }
  return { ok: false, lineaDistinta: null, esperada: null, encontrada: null }
}

function main() {
  let comprometido
  try {
    comprometido = readFileSync(join(RAIZ, GENERADO), 'utf8')
  } catch {
    console.error('')
    console.error(`  check-entorno: FALTA ${GENERADO}`)
    console.error('')
    console.error('  Es el archivo que le da tipos a los bindings, generado desde')
    console.error('  wrangler.jsonc. Se regenera con:')
    console.error('')
    console.error('      npm run tipos:generar')
    console.error('')
    process.exit(1)
  }

  // El temporal va en la RAIZ DEL REPOSITORIO, no en /tmp. No es pereza: el
  // archivo generado contiene `import("./src/index")`, una ruta relativa a su
  // propia ubicacion. Generado en /tmp, wrangler escribe
  // `import("../../root/recargaya-platform/src/index")` y la comparacion nunca
  // puede coincidir.
  //
  // Lleva el pid en el nombre porque dos corridas simultaneas —el CI tiene dos
  // workflows que llaman a `verificar`, y un dev puede tener dos terminales— se
  // pisaban el archivo y una de las dos moria con un ENOENT que se leia como una
  // falla del oraculo. Medido: fallaba en las tres rondas que se probaron.
  const destino = join(RAIZ, `.check-entorno.${process.pid}.temporal.d.ts`)

  // El `finally` de abajo tiene que correr SIEMPRE, asi que nada de `process.exit`
  // adentro del `try`: `process.exit()` termina el proceso de inmediato y el
  // `finally` no corre. La version anterior salia asi en el camino de falla, con
  // un comentario prometiendo que el temporal «se borra solo» — y cada corrida
  // fallida lo dejaba. Se junta el veredicto y se actua despues.
  let fallo = null
  let cmp = null

  try {
    // `shell` en Windows porque ahi `npx` es `npx.cmd` y sin shell da ENOENT.
    // Este archivo normaliza los fines de linea justamente para que el veredicto
    // no cambie entre Windows y Linux; arrancaria mal que no arranque en Windows.
    const r = spawnSync('npx', [...ARGUMENTOS, destino], {
      cwd: RAIZ,
      encoding: 'utf8',
      shell: process.platform === 'win32',
    })
    if (r.status !== 0) {
      fallo = `wrangler types fallo:\n    ${(r.stderr || r.stdout || '').trim().split('\n').slice(-3).join('\n    ')}`
    } else {
      cmp = compararGenerado(comprometido, readFileSync(destino, 'utf8'))
    }
  } catch (e) {
    fallo = e.message
  } finally {
    rmSync(destino, { force: true })
  }

  if (fallo !== null) {
    console.error('')
    console.error('  check-entorno: NO SE PUDO REGENERAR LOS TIPOS')
    console.error('')
    console.error(`    ${fallo}`)
    console.error('')
    process.exit(1)
  }

  {
    if (!cmp.ok) {
      console.error('')
      console.error(`  check-entorno: ${GENERADO} NO COINCIDE CON wrangler.jsonc`)
      console.error('')
      if (cmp.lineaDistinta !== null) {
        console.error(`    primera diferencia, linea ${cmp.lineaDistinta}:`)
        console.error(`      en el repositorio : ${cmp.encontrada}`)
        console.error(`      deberia decir     : ${cmp.esperada}`)
        console.error('')
      }
      console.error('  O cambio la configuracion y nadie regenero los tipos, o alguien edito')
      console.error('  el archivo generado a mano. Las dos cosas terminan igual: el codigo')
      console.error('  compila contra bindings que no existen, y en runtime valen undefined')
      console.error('  sin un solo ruido.')
      console.error('')
      console.error('  Se arregla regenerando, nunca editando:')
      console.error('')
      console.error(`      npm run tipos:generar`)
      console.error('')
      process.exit(1)
    }
  }

  console.log(`  check-entorno: OK — ${GENERADO} coincide con wrangler.jsonc`)
}

if (invocadoDirecto(import.meta.url)) main()
